CREATE DATABASE sample_db;

USE sample_db;

CREATE TABLE `user` (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	
	email VARCHAR(255),
	username VARCHAR(255),
	`password` VARCHAR(255),
	
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	created_by VARCHAR(255) DEFAULT 'system',
	updated_at DATETIME DEFAULT NULL,
	updated_by VARCHAR(255) DEFAULT NULL,
	data_status CHAR(1) DEFAULT 'A'
); 

INSERT INTO `user` (email, username, `password`)
VALUES 
    ('admin@example.com', 'admin', '$2a$10$O.MvCetq0HVcZYOTqej7X.HZMfoxgYChF0nWTC7DKfcLgmvzWfDAG'),
    ('john@example.com', 'john_doe', '$2a$10$YyJ7yS4qjEThMI0DW7C29.sC9Q4/Cf5ZKyRe0HXwfjsOndHhN2G7S'),
    ('jane@example.com', 'jane_smith', '$2a$10$YyJ7yS4qjEThMI0DW7C29.sC9Q4/Cf5ZKyRe0HXwfjsOndHhN2G7S'),
   	('michael@example.com', 'michael_johnson', '$2a$10$YyJ7yS4qjEThMI0DW7C29.sC9Q4/Cf5ZKyRe0HXwfjsOndHhN2G7S'),
  	('emily@example.com', 'emily_brown', '$2a$10$YyJ7yS4qjEThMI0DW7C29.sC9Q4/Cf5ZKyRe0HXwfjsOndHhN2G7S');

 
CREATE TABLE profile (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,

	user_id BIGINT,
	display_name VARCHAR(255),
	birthdate DATETIME,
	birthplace VARCHAR(255),
	
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	created_by VARCHAR(255) DEFAULT 'system',
	updated_at DATETIME DEFAULT NULL,
	updated_by VARCHAR(255) DEFAULT NULL,
	data_status CHAR(1) DEFAULT 'A'
); 

INSERT INTO profile (user_id, display_name, birthdate, birthplace)
VALUES 
    (1, 'Admin User', '1990-01-01', 'New York'),
    (2, 'John Doe', '1995-05-05', 'Los Angeles'),
    (3, 'Jane Smith', '1992-02-02', 'Chicago'),
    (4, 'Michael Johnson', '1988-08-08', 'Houston'),
    (5, 'Emily Brown', '1997-07-07', 'Miami');
   
   
-- auto-generated by Hibernate
CREATE TABLE user_role(
	user_id BIGINT,
	`role` VARCHAR(100)
);

INSERT INTO user_role
VALUES
(1,'ADMIN'),
(2,'CUSTOMER'),
(3,'CUSTOMER'),
(4,'CUSTOMER'),
(5,'CUSTOMER');


CREATE TABLE product (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	price DOUBLE,
	tax DOUBLE,
	
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	created_by VARCHAR(255) DEFAULT 'system',
	updated_at DATETIME DEFAULT NULL,
	updated_by VARCHAR(255) DEFAULT NULL,
	data_status CHAR(1) DEFAULT 'A'
);

INSERT INTO product (name, price, tax)
VALUES
	('Television', 300, 0.1),
	('Refrigerator', 200, 0.15),
	('Washing Machine', 250, 0.2),
	('Fan', 100, 0),
	('Microwave', 150, 0.1),
    ('Air Conditioner', 400, 0.15),
    ('Blender', 50, 0.05);

 
CREATE TABLE transaction_header (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,	
	transaction_time DATETIME,
	customer_id BIGINT,
	payment_method VARCHAR(255),
	payment_status VARCHAR(255),
	
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	created_by VARCHAR(255) DEFAULT 'admin',
	updated_at DATETIME DEFAULT NULL,
	updated_by VARCHAR(255) DEFAULT NULL,
	data_status CHAR(1) DEFAULT 'A'
);

CREATE TABLE transaction_detail (
	id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	header_id BIGINT,
	product_id BIGINT,
	Quantity INT,

	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	created_by BIGINT DEFAULT 0,
	updated_at DATETIME DEFAULT NULL,
	updated_by BIGINT DEFAULT NULL,
	data_status CHAR(1) DEFAULT 'A'
);

INSERT INTO transaction_header (`transaction_time`, customer_id, payment_method, payment_status)
VALUES 
    ('2024-03-10 10:00:00', 1, 'CASH', 'CANCELLED'),
    ('2024-03-11 12:00:00', 2, 'CREDIT', 'PAID'),
	('2024-03-12 14:00:00', 2, 'CASH', 'PAID'),
    ('2024-03-13 16:00:00', 4, 'DEBIT', 'NOT_PAID');

INSERT INTO transaction_detail (header_id, product_id, Quantity)
VALUES 
    (1, 2, 5),
    (1, 1, 3),
    (2, 3, 2),
    (3, 1, 2),
    (3, 3, 1),
    (4, 2, 4);
   
